### PR TITLE
feat: use mcr.microsoft.com/azure-sql-edge image for mssql

### PR DESCRIPTION
**Pull request by ZaoralJ**
use mcr.microsoft.com/azure-sql-edge image for Mssql. There is issue to run mcr.microsoft.com/mssql/server on arm64

### CODE REVIEW

**Comment by Deffiss** [comment]
Hi, @ZaoralJ 
I don't believe this is reasonable to make the default image here. Also, seems Azure SQL Edge is not exactly the same as just usual MSSQL Server. However, for your project needs you can easily use required image, just by specifying **ImageName** in params:

```
                .AddMssqlContainer(p => p with
                {
                    ImageName = "mcr.microsoft.com/azure-sql-edge",
                    Name = "my-mssql",
```

**Comment by ZaoralJ** [comment]
> Hi, @ZaoralJ I don't believe this is reasonable to change the default image here. Seems Azure SQL Edge is not exactly the same as just usual MSSQL Server. However, for your project needs you can easily use required image, just by specifying **ImageName** in params:
> 
> ```
>                 .AddMssqlContainer(p => p with
>                 {
>                     ImageName = "mcr.microsoft.com/azure-sql-edge",
>                     Name = "my-mssql",
> ```

Hi @Deffiss,
that was the first think I've tried. There is problem with forced env ["MSSQL_PID"] = "Express", valid value for azure sql edge is Developer or Premium. Developer PID is default for SQL server.
What about remove ["MSSQL_PID"] = "Express" or new nuget for AzureSqlEdge?

**Comment by Deffiss** [comment]
Let me check the code, probably you can just override.

**Comment by Deffiss** [comment]
Or, I can fix the logic for **AddMssqlContainer** and do not override MSSQL_PID parameter if it is provided. What will work better for you?

**Comment by ZaoralJ** [comment]
> Ok how about adding Azure SQL Edge specific extension method? It will be something like **.AzureSqlEdgeContainer()**. You can use a basic version of **AddMssqlContainer** but adjust the logic to use appropriate base image and specify proper MSSQL_PID
> 
> 

I can make PR for new AzureSqlEdgeContainer. It might be handy.

**Comment by ZaoralJ** [comment]
Open #73 to support AzureSqlEdge

**Pull request closed without merging**
